version: '3.8'

services:
  svc-python-app:
    build:
      dockerfile: Dockerfile
    container_name: cn-script-executor
    image: script-executor-image
    hostname: script-executor
    environment:
      TITLE: 'Python Script Executor'
      VERSION: '0.0.1'
      APP_ENV: prod
      APP_USERNAME_AND_PASSWORD: 'user,pass'
    ports:
      - "9595:8080"
